/*
 * generated by Xtext
 */
package de.peeeq.wolf.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class WolfUiModule extends de.peeeq.wolf.ui.AbstractWolfUiModule {
	public WolfUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
