/*
 * generated by Xtext
 */
package de.peeeq.wolf.ui.contentassist

import de.peeeq.wolf.ui.contentassist.AbstractWolfProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
class WolfProposalProvider extends AbstractWolfProposalProvider {
}
