/*
 * generated by Xtext
 */
package de.peeeq.wolf;

import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.eclipse.xtext.scoping.IGlobalScopeProvider;
import org.eclipse.xtext.scoping.IScopeProvider;
import org.eclipse.xtext.xbase.scoping.batch.ImplicitlyImportedTypes;

import com.google.inject.Binder;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class WolfRuntimeModule extends de.peeeq.wolf.AbstractWolfRuntimeModule {

	
	
	
	@Override
	public void configure(Binder binder) {
		super.configure(binder);
//		binder.bind(IScopeProvider.class).to(WolfScopeProvider.class);
//		binder.bind(IQualifiedNameProvider.class).to(WolfQualifiedNameProvider.class); 
	}
	
	@Override
	public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
		return WolfQualifiedNameProvider.class;
	}
	
	
}
	
