/*
* generated by Xtext
*/
package de.peeeq.wolf;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class WolfStandaloneSetup extends WolfStandaloneSetupGenerated{

	public static void doSetup() {
		new WolfStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

